name: Server test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, windows-latest]
        mongodb-version: [4.0, 4.4]
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Uses MongoDB version ${{matrix.mongodb-version}}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - name: Installing dependencies and running tests
        run: |
          cd server
          npm install
          npm test
